services:
  - type: web
    name: morning-summary-station
    env: python
    runtime: python3.9
    buildCommand: bash build.sh
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCUWEATHER_API_KEY
        sync: false
      - key: LOCATION
        value: London
      - key: ADDRESS
        value: 16 acer road, dalston - E83GX
      - key: GOOGLE_CALENDAR_ID
        value: primary
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
    autoDeploy: true 